// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8yC9Qu534vrUUMd4v2mKXbv41a4aNaxs',
    appId: '1:481862748682:web:b1856d9439aefc98beedf3',
    messagingSenderId: '481862748682',
    projectId: 'alot-c1f1b',
    authDomain: 'alot-c1f1b.firebaseapp.com',
    storageBucket: 'alot-c1f1b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2A9JgzQqfW1ub6th4AEEcA2eGq_ZMec8',
    appId: '1:481862748682:android:093e055c3612468cbeedf3',
    messagingSenderId: '481862748682',
    projectId: 'alot-c1f1b',
    storageBucket: 'alot-c1f1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo4hFa7kKzEFkinXVqW-Tz2hQCddzySn0',
    appId: '1:481862748682:ios:c5d7c08b771c7223beedf3',
    messagingSenderId: '481862748682',
    projectId: 'alot-c1f1b',
    storageBucket: 'alot-c1f1b.appspot.com',
    iosBundleId: 'com.example.alotMobiledevelopment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo4hFa7kKzEFkinXVqW-Tz2hQCddzySn0',
    appId: '1:481862748682:ios:c5d7c08b771c7223beedf3',
    messagingSenderId: '481862748682',
    projectId: 'alot-c1f1b',
    storageBucket: 'alot-c1f1b.appspot.com',
    iosBundleId: 'com.example.alotMobiledevelopment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8yC9Qu534vrUUMd4v2mKXbv41a4aNaxs',
    appId: '1:481862748682:web:bf80ccd78031f43dbeedf3',
    messagingSenderId: '481862748682',
    projectId: 'alot-c1f1b',
    authDomain: 'alot-c1f1b.firebaseapp.com',
    storageBucket: 'alot-c1f1b.appspot.com',
  );
}
